### ISSUE TITLE
New ae-debugging

### ISSUE THREAD

**Issue by sjuergen** [simatic-ax/ae-debugging#1]
@marosiag 

I've seen there's new repo created. Thanks for contributing to the SIMATIC AX Community. 

But before we create a new repo, some stuff has to be clarified/done:

- What is the purpose for that repo? Could you describe it in a view sentences?
- Who cares about the OSS, patent, ECC clearing? (https://github.com/simatic-ax/.github-private/blob/main/docs/createrepo.md). If you need support, please contact me. 
- This repo contains just a Readme.md. It should have at minimum a valid license and codeowners file. Therefore there are some predefined apax templates which have to be used. 

Thanks and regards
@sjuergen

**Comment by marosiag** [comment]
Hey @sjuergen,
sorry for the late reply. This repository will contain a debugging example for the documentation regarding debugging. As of now the example is part of the documentation and the user has to copy/paste it. As the product envolves the example is getting bigger and it's not feasible to copy/paste it.

**Comment by marosiag** [comment]
All points are fullfilled. Repository is now public.
